services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: bobmarley420
      MYSQL_DATABASE: mysqlombra
    ports:
      - "3306:3306"
    volumes:
      - ./datannabis/cannabscript.sql:/docker-entrypoint-initdb.d/cannabscript.sql


