services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: bobmarley420
      MYSQL_DATABASE: mysqlombra
    ports:
      - "3306:3306"
    volumes:
      - ./datannabis/cannabscript.sql:/docker-entrypoint-initdb.d/cannabscript.sql


  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
